- name: Update homebrew 
  homebrew: update_homebrew=yes

- name: Install homebrew tap packages
  homebrew_tap: name={{ item }}
  tags: homebrew
  ignore_errors: yes
  loop:
    - "{{ BREWTAP_TARGETS }}" 

- name: Install homebrew packages
  homebrew: name={{ item }}
  tags: homebrew
  ignore_errors: yes
  loop:
    - "{{ BREW_TARGETS }}"

- name: Install python 3.7.7 
  tags: homebrew
  ignore_errors: yes
  shell: pyenv install 3.7.7 && pyenv global 3.7.7

- name: Install pip 
  tags: homebrew
  shell: sudo easy_install pip

- name: upgrade pip 
  tags: homebrew
  shell: sudo pip install --upgrade pip

